import { defineStore } from "pinia";

export const useStore = defineStore("store", {
  state: () => ({
    data_set_priority: [
      {
        id: 1,
        full_name: "Иванов Александр Сергеевич",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Москва",
        training_program: "охрана труда",
        passed_date: "12.05.2023",
        expired_date: "15.11.2026",
        priority: "Истекает",
      },
      {
        id: 2,
        full_name: "Петрова Елена Александровна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Казань",
        training_program: "пожарная безопасность",
        passed_date: "23.09.2022",
        expired_date: "30.06.2025",
        priority: "Активен",
      },
      {
        id: 3,
        full_name: "Сидоров Дмитрий Николаевич",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Екатеринбург",
        training_program: "работа на высоте",
        passed_date: "14.02.2024",
        expired_date: "20.07.2025",
        priority: "Активен",
      },
      {
        id: 4,
        full_name: "Кузнецова Анна Михайловна",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Самара",
        training_program: "охрана труда",
        passed_date: "01.11.2021",
        expired_date: "15.07.2027",
        priority: "Просрочен",
      },
      {
        id: 5,
        full_name: "Смирнов Игорь Петрович",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Ростов-на-Дону",
        training_program: "пожарная безопасность",
        passed_date: "07.08.2023",
        expired_date: "10.02.2026",
        priority: "Истекает",
      },
      {
        id: 6,
        full_name: "Федоров Сергей Иванович",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Новосибирск",
        training_program: "работа на высоте",
        passed_date: "19.03.2022",
        expired_date: "25.09.2025",
        priority: "Активен",
      },
      {
        id: 7,
        full_name: "Соколова Ольга Дмитриевна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Челябинск",
        training_program: "охрана труда",
        passed_date: "10.06.2024",
        expired_date: "15.12.2025",
        priority: "Истекает",
      },
      {
        id: 8,
        full_name: "Яковлев Михаил Алексеевич",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Омск",
        training_program: "пожарная безопасность",
        passed_date: "25.01.2021",
        expired_date: "30.07.2028",
        priority: "Просрочен",
      },
      {
        id: 9,
        full_name: "Попова Наталья Сергеевна",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Уфа",
        training_program: "работа на высоте",
        passed_date: "03.04.2023",
        expired_date: "10.10.2024",
        priority: "Контроль",
      },
      {
        id: 10,
        full_name: "Михайлов Дмитрий Николаевич",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Санкт-Петербург",
        training_program: "охрана труда",
        passed_date: "17.07.2022",
        expired_date: "20.01.2026",
        priority: "Истекает",
      },
      {
        id: 11,
        full_name: "Иванова Татьяна Петровна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Москва",
        training_program: "пожарная безопасность",
        passed_date: "29.11.2023",
        expired_date: "05.05.2027",
        priority: "Просрочен",
      },
      {
        id: 12,
        full_name: "Петров Игорь Александрович",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Казань",
        training_program: "работа на высоте",
        passed_date: "15.02.2022",
        expired_date: "20.08.2025",
        priority: "Активен",
      },
      {
        id: 13,
        full_name: "Сидорова Елена Михайловна",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Екатеринбург",
        training_program: "охрана труда",
        passed_date: "08.09.2024",
        expired_date: "15.03.2026",
        priority: "Истекает",
      },
      {
        id: 14,
        full_name: "Кузнецов Сергей Дмитриевич",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Самара",
        training_program: "пожарная безопасность",
        passed_date: "22.04.2021",
        expired_date: "30.10.2027",
        priority: "Просрочен",
      },
      {
        id: 15,
        full_name: "Смирнова Анна Николаевна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Ростов-на-Дону",
        training_program: "работа на высоте",
        passed_date: "12.12.2023",
        expired_date: "20.06.2025",
        priority: "Контроль",
      },
      {
        id: 16,
        full_name: "Федоров Александр Сергеевич",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Новосибирск",
        training_program: "охрана труда",
        passed_date: "05.03.2022",
        expired_date: "10.09.2026",
        priority: "Истекает",
      },
      {
        id: 17,
        full_name: "Соколова Ольга Ивановна",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Челябинск",
        training_program: "пожарная безопасность",
        passed_date: "19.06.2024",
        expired_date: "25.12.2025",
        priority: "Истекает",
      },
      {
        id: 18,
        full_name: "Яковлев Дмитрий Петрович",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Омск",
        training_program: "работа на высоте",
        passed_date: "01.08.2021",
        expired_date: "15.02.2028",
        priority: "Просрочен",
      },
      {
        id: 19,
        full_name: "Попова Елена Алексеевна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Уфа",
        training_program: "охрана труда",
        passed_date: "27.10.2023",
        expired_date: "05.04.2026",
        priority: "Истекает",
      },
      {
        id: 20,
        full_name: "Михайлова Наталья Сергеевна",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Санкт-Петербург",
        training_program: "пожарная безопасность",
        passed_date: "14.01.2022",
        expired_date: "20.07.2025",
        priority: "Активен",
      },
      {
        id: 21,
        full_name: "Иванов Сергей Михайлович",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Москва",
        training_program: "работа на высоте",
        passed_date: "03.05.2024",
        expired_date: "10.11.2025",
        priority: "Истекает",
      },
      {
        id: 22,
        full_name: "Петрова Анна Николаевна",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Казань",
        training_program: "охрана труда",
        passed_date: "18.09.2021",
        expired_date: "25.03.2028",
        priority: "Просрочен",
      },
      {
        id: 23,
        full_name: "Сидоров Игорь Александрович",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Екатеринбург",
        training_program: "пожарная безопасность",
        passed_date: "07.02.2023",
        expired_date: "15.08.2025",
        priority: "Активен",
      },
      {
        id: 24,
        full_name: "Кузнецова Ольга Дмитриевна",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Самара",
        training_program: "работа на высоте",
        passed_date: "22.11.2022",
        expired_date: "30.05.2026",
        priority: "Истекает",
      },
      {
        id: 25,
        full_name: "Смирнов Александр Петрович",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Ростов-на-Дону",
        training_program: "охрана труда",
        passed_date: "09.04.2024",
        expired_date: "15.10.2025",
        priority: "Истекает",
      },
      {
        id: 26,
        full_name: "Федорова Елена Сергеевна",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Новосибирск",
        training_program: "пожарная безопасность",
        passed_date: "16.07.2021",
        expired_date: "20.01.2028",
        priority: "Просрочен",
      },
      {
        id: 27,
        full_name: "Соколова Наталья Ивановна",
        category_job: "служащий",
        category: "бухгалтер",
        branch_id: "Челябинск",
        training_program: "работа на высоте",
        passed_date: "28.12.2023",
        expired_date: "05.06.2025",
        priority: "Контроль",
      },
      {
        id: 28,
        full_name: "Яковлев Михаил Николаевич",
        category_job: "руководитель",
        category: "директор",
        branch_id: "Омск",
        training_program: "охрана труда",
        passed_date: "11.03.2022",
        expired_date: "15.09.2026",
        priority: "Истекает",
      },
      {
        id: 29,
        full_name: "Попов Сергей Алексеевич",
        category_job: "инженер",
        category: "оператор",
        branch_id: "Уфа",
        training_program: "пожарная безопасность",
        passed_date: "04.06.2024",
        expired_date: "10.12.2025",
        priority: "Истекает",
      },
      {
        id: 30,
        full_name: "Михайлова Анна Петровна",
        category_job: "рабочий",
        category: "инженер",
        branch_id: "Санкт-Петербург",
        training_program: "работа на высоте",
        passed_date: "20.08.2022",
        expired_date: "25.02.2026",
        priority: "Истекает",
      },
    ],
    table_headers_priority: [
      { id: 1, label: "Ф.И.О.", key: "full_name" },
      { id: 2, label: "Категория должности", key: "category_job" },
      { id: 3, label: "Должность", key: "category" },
      { id: 4, label: "Филиал", key: "branch_id" },
      { id: 5, label: "Допуск", key: "training_program" },
      { id: 6, label: "Дата получения", key: "passed_date" },
      { id: 7, label: "Дата окончания", key: "expired_date" },
      { id: 8, label: "Статус", key: "priority" },
    ],
    set_priority: [
      { name: "Просрочен" },
      { name: "Истекает" },
      { name: "Контроль" },
      { name: "Активен" },
    ],
    token: localStorage.getItem("access_token") || null,
    userRole: "",
  }),
  getters: {
    mockUsers: (state) => state.mock_users,
    DataSetPriority: (state) => state.data_set_priority,
    TableHeadersPriority: (state) => state.table_headers_priority,
    SetPriority: (state) => state.set_priority,
    isAuth: (state) => !!state.token,
  },
  actions: {
    setToken(token) {
      this.token = token;
    },
    setUserRole(userRole) {
      this.userRole = userRole;
    },
    clearToken() {
      this.token = null;
      localStorage.removeItem("access_token");
    },
  },
});
