---
- name: Deploy project with .env
  hosts: all

  tasks:
    - name: Ensure .env file exists
      ansible.builtin.file:
        path: "/opt/sapg/.env"
        state: touch
        mode: '0644'

    - name: Update FRONTEND_IMAGE_TAG in .env
      ansible.builtin.lineinfile:
        path: "/opt/sapg/.env"
        regexp: "^FRONTEND_IMAGE_TAG="
        line: "FRONTEND_IMAGE_TAG={{ app_version }}"
        create: yes

    - name: Start docker compose
      ansible.builtin.shell: docker compose -f /opt/sapg/docker-compose-prod.yaml up -d
